# Generated by Django 3.2.4 on 2021-06-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6)),
                ('salary', models.IntegerField()),
                ('team', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
